// eslint-disable-next-line
export const modalTypes = {
  SET_MODAL_VISIBILITY_START: 'SET_MODAL_VISIBILITY_START',
  SET_MODAL_VISIBILITY_SUCCESS: 'SET_MODAL_VISIBILITY_SUCCESS',
  SET_MODAL_VISIBILITY_FAILURE: 'SET_MODAL_VISIBILITY_FAILURE'
};
