// eslint-disable-next-line
export const PostTypes = {
  ASK_PERMISSION_START: 'ASK_PERMISSION_START',
  ASK_PERMISSION_SUCCESS: 'ASK_PERMISSION_SUCCESS',
  ASK_PERMISSION_FAILURE: 'ASK_PERMISSION_FAILURE',

  SET_MULTIPLE_IMAGE_START: 'SET_MULTIPLE_IMAGE_START',
  SET_MULTIPLE_IMAGE_SUCCESS: 'SET_MULTIPLE_IMAGE_SUCCESS',

  SET_MEDIA_START: 'SET_MEDIA_START',
  SET_MEDIA_SUCCESS: 'SET_MEDIA_SUCCESS',
  SET_MEDIA_FAILURE: 'SET_MEDIA_FAILURE',

  SET_DEFAULT_IMAGE: 'SET_DEFAULT_IMAGE',

  SET_ALBUM_NAME_START: 'SET_ALBUM_NAME_START',
  SET_ALBUM_NAME_SUCCESS: 'SET_ALBUM_NAME_SUCCESS',
  SET_ALBUM_NAME_FAILURE: 'SET_ALBUM_NAME_FAILURE',

  EMPTY_START: 'EMPTY_START',
  EMPTY_SUCCESS: 'EMPTY_SUCCESS',

  ADD_IMAGE_START: 'ADD_IMAGE_START',
  ADD_IMAGE_SUCCESS: 'ADD_IMAGE_SUCCESS',

  GET_ALBUM_LIST_START: 'GET_ALBUM_LIST_START',
  GET_ALBUM_LIST_SUCCESS: 'GET_ALBUM_LIST_SUCCESS',
  GET_ALBUM_LIST_FAILURE: 'GET_ALBUM_LIST_FAILURE',

  REMOVE_IMAGE_START: 'REMOVE_IMAGE_START',
  REMOVE_IMAGE_SUCCESS: 'REMOVE_IMAGE_SUCCESS',

  EMPTY_MEDIA_START: 'EMPTY_MEDIA_START',
  EMPTY_MEDIA_SUCCESS: 'EMPTY_MEDIA_SUCCESS',
};
