// eslint-disable-next-line
export const profileActionTypes = {
  GET_PROFILE_START: 'GET_PROFILE_START',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  SET_USER_PROFILE: 'SET_USER_PROFILE',
  SET_MODAL_VISIBLE: 'SET_MODAL_VISIBLE'
};
