export const userActionTypes = {
     SEND_EMAIL_CONFIRMATION_CODE_START: 'SEND_EMAIL_CONFIRMATION_CODE_START',
     SEND_EMAIL_CONFIRMATION_CODE_SUCCESS: 'SEND_EMAIL_CONFIRMATION_CODE_SUCCESS',
     SEND_EMAIL_CONFIRMATION_CODE_FAILURE: 'SEND_EMAIL_CONFIRMATION_CODE_FAILURE',

     VERIFY_CONFIRMATION_CODE_START: 'VERIFY_CONFIRMATION_CODE_START',
     VERIFY_CONFIRMATION_CODE_SUCCESS: 'VERIFY_CONFIRMATION_CODE_SUCCESS',
     VERIFY_CONFIRMATION_CODE_FAILURE: 'VERIFY_CONFIRMATION_CODE_FAILURE',

     REGISTER_START: 'REGISTER_START',
     REGISTER_SUCCESS: 'REGISTER_SUCCESS',
     REGISTER_FAILURE: 'REGISTER_FAILURE',

     LOGIN_START: 'LOGIN_START',
     LOGIN_SUCCESS: 'LOGIN_SUCCESS',
     LOGIN_FAILURE: 'LOGIN_FAILURE',

     SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
     SIGN_OUT_START: 'SIGN_OUT_START',
     SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

     SET_CURRENT_USER: 'SET_CURRENT_USER',
     AUTH_ERROR: 'AUTH_ERROR'




}